### ISSUE TITLE
how to keep the order while using dict_of

### ISSUE THREAD

**Issue by sant527** [alexmojaki/sorcery#9]
i am using

```
print(dict_of(z_1,c_2,b_3))
it prints in the order

b_3
c_2
z_1
```

How to keep the same order as i mentioned

**Comment by alexmojaki** [comment]
What version of Python are you using? In recent versions it should be ordered automatically. 

You can take the source of dict_of:

https://github.com/alexmojaki/sorcery/blob/a19dc97a10f8b9cc1c098ee0d2d297ffb2e0d6d6/sorcery/spells.py#L244-L289

And just use an OrderedDict with a list comprehension of pairs instead of a regular dict comprehension.

**Comment by sant527** [comment]
Sorry, i was using json dump and set sort True.

I thought this is causing the problem
